# Change these first
owner: upptime # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Comcast office
    check: "tcp-ping"
    url: 50.211.130.193
    __dangerous__disable_verify_peer: true
  - name: Windstream office
    check: "tcp-ping"
    url: 71.16.153.90
    __dangerous__disable_verify_peer: true
  - name: Sharepoint sties
    url: https://nacgroup.sharepoint.com/sites/InternalIT
  
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime for NAC Mechanical Services
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is the seb services status page for NAC Mechanical Services.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
